version: '3.8'

services:
  web:
    build: .
    container_name: ecommerce_fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Instead of hardcoding environment variables, we tell Docker to load them all from .env!
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: ecommerce_celery_worker
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    # Load env variables for database, redis, and smtp connection
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: ecommerce_mysql
    restart: always
    environment:
      # We reference the variables from the .env file using ${VAR_NAME} syntax
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
