"""Add unique constraints to role mappings

Revision ID: d12efe068f2d
Revises: 03514cf0b0ba
Create Date: 2026-06-01 10:22:09.675475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12efe068f2d'
down_revision: Union[str, Sequence[str], None] = '03514cf0b0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.create_unique_constraint('uq_user_permission', 'user_permissions', ['user_id', 'permission_id'])
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_user_permission', 'user_permissions', type_='unique')
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    # ### end Alembic commands ###
